name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libs: [core,components,auth,form-builder,components-bootstrap,form-builder-bootstrap]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
            registry-url: 'https://registry.npmjs.org'
      - name: test
        run: |
          echo ${{ matrix.libs }}.scss
      - name: install deps
        run: npm install
      - name: publish to npm
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
      - name: dist dir
        run: cd dist && ls -l
