name: Angular

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@main
            -   uses: actions/setup-node@v1
                with:
                    node-version: '12'
                    registry-url: 'https://registry.npmjs.org'

            -   name: install deps
                run: npm ci

            -   name: build packages
                run: npm run build

            -   name: Publish
                run: |
                    npm run publish
                    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_KEY }}" > ~/.npmrc
