name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
            registry-url: 'https://registry.npmjs.org'
      - name: install angular cli
        run: sudo npm install -g @angular/cli@10.0.6
      - name: install deps
        run: npm install
      - name: build packages
        run: for f in $libs; do sudo ng build --project $f --prod && sudo npm i ; done
        env:
          libs: core components auth form-builder components-bootstrap form-builder-bootstrap
      - name: install optional deps
        run: npm i
      - name: build packages
        run: for f in $libs; do npm publish dist/$f --access public ; done
        env:
          libs: core components auth form-builder components-bootstrap form-builder-bootstrap
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
      - name: dist dir
        run: cd dist && ls -l
