name: Angular

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
            node-version: '12'
            registry-url: 'https://registry.npmjs.org'
      - name: install deps
        run: npm install
      - name: publish to npm
        run: for f in $libs; do ng build --project $f --prod && npm i && npm publish dist/$f --access public ; done
        env:
          libs: core components auth form-builder components-bootstrap form-builder-bootstrap
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
      - name: dist dir
        run: cd dist && ls -l
